name: Supabase Keep Alive

on:
  schedule:
    - cron: "0 2 * * *" # 9 AM WIB
  workflow_dispatch: # Manual

jobs:
  call-health-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call /health endpoint to keep Supabase alive
        run: |
          curl -X GET "https://ryplay.fachryafrz.com/api/health?secret=${{ secrets.HEALTH_SECRET }}"
